### ISSUE TITLE
Deployed model locally, what next?

### ISSUE THREAD

**Issue by zackooi** [cstub/ml-ids#18]
Hi anyone able to use the model after deploying it locally? I had successfully deployed the model locally, but I had no idea how to use it to scan the traffic.

**Comment by wealthray** [comment]
hey i am getting TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
Traceback (most recent call last):
  File "./models/gradient_boost/envs/local/train.py", line 51, in <module>
    train()
can you tell me what might be the issue

**Comment by bipulbhattarai** [comment]
hey i am getting TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
Traceback (most recent call last):
File "./models/gradient_boost/envs/local/train.py", line 51, in
train()
can you tell me what might be the issue
